In [1]:
using Pkg
pkg"add BenchmarkTools"

   Updating registry at `C:\Users\rodri\.julia\registries\General`
  Resolving package versions...
  Installed BenchmarkTools ─ v0.5.0
Updating `C:\Users\rodri\.julia\environments\v1.5\Project.toml`
  [6e4b80f9] + BenchmarkTools v0.5.0
Updating `C:\Users\rodri\.julia\environments\v1.5\Manifest.toml`
  [6e4b80f9] + BenchmarkTools v0.5.0


"@benchmark função()" para retornar o benchmark da **função**

# Sistemas Lineares

In [2]:
A = rand(3, 3)
b = A * ones(3)

3-element Array{Float64,1}:
 1.6351667710572018
 1.2928110146685157
 1.1637898217900702

In [3]:
A \ b

3-element Array{Float64,1}:
 1.0
 1.0
 1.0

## Eliminação Gaussiana

Usar múltiplos de linhas anteriores para zerar colunas de outras linhas

#### 1ª Coluna: $L_1$ é usada como pivô (é preciso que $a_{11} ≠ 0$), de modo que zere a 1ª coluna das outras linhas

In [16]:
A = [3.0 1 2; -1 2 1; 1 1 4]

3×3 Array{Float64,2}:
  3.0  1.0  2.0
 -1.0  2.0  1.0
  1.0  1.0  4.0

In [17]:
b = A * ones(3)

3-element Array{Float64,1}:
 6.0
 2.0
 6.0

In [18]:
m21 = A[2,1] / A[1,1]
m31 = A[3,1] / A[1,1]

# Para pegar uma linha inteira da matriz: A[número da linha, :]
A[2, :] = A[2, :] - m21 * A[1,:]
A[3, :] = A[3, :] - m31 * A[1,:]

3-element Array{Float64,1}:
 0.0
 0.6666666666666667
 3.3333333333333335

In [19]:
b[2] = b[2] - m21 * b[1]
b[3] = b[3] - m31 * b[1]

b

3-element Array{Float64,1}:
 6.0
 4.0
 4.0

In [20]:
A # 1ª coluna eliminada

3×3 Array{Float64,2}:
 3.0  1.0       2.0
 0.0  2.33333   1.66667
 0.0  0.666667  3.33333

No caso acima não foi calculado o $b$ do sistema $Ax = b$ na eliminação gaussiana, mas ele sempre tem que ser calculado junto com $A$

#### 2ª Coluna: $L_2$ é pivô, $L_3 = L_3 - m_{32}L_2$...

In [21]:
m32 = A[3,2] / A[2,2]
A[3, :] -= m32 * A[2,:]
b[3] -= m32 * b[2]

A

3×3 Array{Float64,2}:
 3.0   1.0          2.0
 0.0   2.33333      1.66667
 0.0  -1.11022e-16  2.85714

In [22]:
A \ b

3-element Array{Float64,1}:
 1.0
 1.0000000000000002
 0.9999999999999999

Pode acontecer da eliminação gerar uma matriz muito diferente da inicial devido ao ponto flutuante (Matriz mal condicionada)

In [36]:
function elim_gauss!(A, b)
    m, n = size(A)
    for j = 1:n
        cols = j+1:n
        for i = j+1:m
            mij = A[i,j]
            A[i,cols] -= mij * A[j,cols]
            A[i,j] = 0.0
            b[i] -= mij * b[j]
        end
    end
end

elim_gauss! (generic function with 2 methods)

In [37]:
A = rand(6, 5)
b = A  * ones(5)

6-element Array{Float64,1}:
 3.3719667438949514
 2.563187920373945
 3.1713688200162715
 2.7351038804519785
 1.592138452521397
 3.3308852548581704

In [38]:
A

6×5 Array{Float64,2}:
 0.739488  0.758197  0.760841   0.291798   0.821642
 0.308769  0.459562  0.83537    0.56975    0.389737
 0.952614  0.135502  0.773778   0.721517   0.587958
 0.90304   0.217202  0.715428   0.835488   0.0639465
 0.4684    0.166506  0.0372363  0.0267241  0.893272
 0.560673  0.946057  0.707657   0.573991   0.542506

In [39]:
elim_gauss!(A, b)

In [40]:
A

6×5 Array{Float64,2}:
 0.739488  0.758197  0.760841  0.291798   0.821642
 0.0       0.225454  0.600446  0.479651   0.136039
 0.0       0.0       0.401312  0.724989  -0.114926
 0.0       0.0       0.0       0.572149  -0.578915
 0.0       0.0       0.0       0.0        0.58555
 0.0       0.0       0.0       0.0        0.0

In [41]:
b

6-element Array{Float64,1}:
 3.3719667438949514
 1.5220286194290882
 0.8522630331871314
 0.13820633179897512
 0.4573407114687179
 0.5971501386897078

Se der 0 na última coluna de $b$ a solução é impossível